targets:
  $default:
    builders:
      class_namer:
        enabled: true
        generate_for:
          exclude:
            - test
          include:
            - test/integration/*

builders:
  class_namer:
    import: "package:class_namer/class_namer.dart"
    builder_factories: ["classNamer"]
    build_extensions: { ".dart": [".names.dart"] }
    auto_apply: dependents
    build_to: source